# Usamos la imagen oficial de OpenJDK
FROM openjdk:21

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el JAR generado por Spring Boot
COPY target/s4-product-service-0.0.1-SNAPSHOT.jar app.jar

# Exponemos el puerto en el que corre la app (configurado en application.properties)
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]